language: ruby
bundler_args: --without "oracle sqlserver"

before_script:
  - cp test/connections/databases.ci.yml test/connections/databases.yml
  - bundle exec rake mysql:build_database postgresql:build_database sqlite:build_database

script:
  - "bundle exec rake postgresql:test"
  - "bundle exec rake sqlite:test"
  - "bundle exec rake mysql:test"

env:
  global:
    - CPK_LOGFILE=log/test.log

matrix:
  include:
    - name: "Ruby 2.6 with Rails 6"
      rvm: 2.6.3
      env: RAILS_VERSION="~> 6.0.0.beta3"
    - name: "Ruby 2.5 with Rails 6"
      rvm: 2.5.5
      env: RAILS_VERSION="~> 6.0.0.beta3"
    - name: "Ruby 2.4 with Rails 5"
      rvm: 2.4.6
      env: RAILS_VERSION="~> 5.2"

addons:
  postgresql: "9.4"

services:
  - postgresql
