language: ruby
sudo: false

before_script:
  - cp test/connections/databases.ci.yml test/connections/databases.yml
  - rake mysql:build_database postgresql:build_database sqlite3:build_database

script:
  - "rake postgresql:test"
  - "rake sqlite3:test"
  - "rake mysql:test"

rvm:
  - 2.2.2
  - 2.3.0

env:
  - CPK_LOGFILE=log/test.log