language: ruby
bundler_args: --without "oracle sqlserver"

before_script:
  - cp test/connections/databases.ci.yml test/connections/databases.yml
  - bundle exec rake mysql:build_database postgresql:build_database

script:
  - "bundle exec rake postgresql:test"
  - "bundle exec rake mysql:test"

rvm:
  - 2.5.7
  - 2.6.5
  - 2.7.0

env:
  global:
    - CPK_LOGFILE=log/test.log

services:
  - postgresql
  - mysql
