language: ruby
bundler_args: --without "oracle sqlserver"
addons:
  postgresql: 11.5

before_script:
  - cp test/connections/databases.ci.yml test/connections/databases.yml
  - bundle exec rake mysql:build_database postgresql:build_database sqlite:build_database

script:
  - "bundle exec rake postgresql:test"
  - "bundle exec rake sqlite:test"
  - "bundle exec rake mysql:test"

rvm:
  - 2.5.5
  - 2.6.3

env:
  global:
    - CPK_LOGFILE=log/test.log

services:
  - postgresql
  - mysql
